@dic.add_rule( [1,"set_param_values"], [:setparam], lambda { |obj,args,nxt|

   d = @dic.get_data( args ) # если делать тут вычисление @edic... то появляются кавычки..

   tgt_prop = obj[:prop] || "value"
   
   [{ :tag => :expression, :expression => "param_#{convert_data_name obj[:name]}.#{tgt_prop} = /* assign generated by 4-params/epass */ ", :items => [d] }]
})
